version: 2.1
# Use a package of configuration called an orb.

jobs:
  # create_infrastructure: 
  #     docker:
  #       - image: amazon/aws-cli
  #     steps:
  #       - checkout
  #       - run:
  #           name: Create Cloudformation Stack
  #           command: |
  #             aws cloudformation deploy \
  #               --template-file template.yml \
  #               --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #               --region us-east-1
  configure_infrastructure:
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints: ["d6:6d:92:43:67:95:a6:26:5e:15:02:15:03:e1:43:77"]
        
        - run:
            name: Install Ansible
            command: |
              # install the dependencies needed for your playbook
              apk add --update ansible 
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory.txt main4.yml
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      #- create_infrastructure
      - configure_infrastructure